"""Init

Revision ID: e79a9868b02e
Revises: 
Create Date: 2023-05-11 14:37:17.461212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79a9868b02e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('GroupId', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('GroupId')
    )
    op.create_table('teachers',
    sa.Column('TeacherId', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('TeacherId')
    )
    op.create_table('students',
    sa.Column('StudentId', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=50), nullable=False),
    sa.Column('GroupId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['GroupId'], ['groups.GroupId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('StudentId')
    )
    op.create_table('subjects',
    sa.Column('SubjectId', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=50), nullable=False),
    sa.Column('TeacherId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['TeacherId'], ['teachers.TeacherId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SubjectId')
    )
    op.create_table('marks',
    sa.Column('MarkId', sa.Integer(), nullable=False),
    sa.Column('StudentId', sa.Integer(), nullable=True),
    sa.Column('SubjectId', sa.Integer(), nullable=True),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.Column('mark_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['StudentId'], ['students.StudentId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SubjectId'], ['subjects.SubjectId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('MarkId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    op.drop_table('subjects')
    op.drop_table('students')
    op.drop_table('teachers')
    op.drop_table('groups')
    # ### end Alembic commands ###
